list: $/travis/contact/models/message/columns.yaml
modelClass: Travis\Contact\Models\Message
title: Messages
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'travis/contact/messages/update/:id'
